removes ip as an argument for the functions identify_using_ssl_cert(), get_certs_from_handshake() and the functions in the lib/ directory that are called in lift.py. TypeError: recurse_DNS_check() got an unexpected keyword argument 'subnet' was raised in process_ip() and I think getting rid of 'ip' as an input to the functions could help.